pyasn1/coded/ber: Fix regressions dealing component == None
since commit 4f644c59bf3ec34a3a8b9cd045dfd7cd1735259f

  #!/usr/bin/env python3
  import sys, os.path, io, string
  import base64

  from pyasn1.codec.der.decoder import decode as pyasn1_der_decode

  def main ():
      blob = "fk8wTaADAgEFoQMCAR6kERgPMjAyMzA2MDYxMDAxMTlapQU"\
              "CAwIstqYDAgEsqRUbEzx1bnNwZWNpZmllZCByZWFsbT6qCzAJoAMCAQChAjAA"
      obj, _ = pyasn1_der_decode(base64.b64decode(blob))
  if __name__ == '__main__':
      main()

results in

  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 2003, in __call__
    for asn1Object in streamingDecoder:
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 1918, in __iter__
    for asn1Object in self._singleItemDecoder(
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 1778, in __call__
    for value in concreteDecoder.valueDecoder(
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 99, in valueDecoder
    for value in decodeFun(substrate, asn1Spec, tagSet, length, **options):
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 1778, in __call__
    for value in concreteDecoder.valueDecoder(
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 660, in valueDecoder
    for asn1Object in self._decodeComponentsSchemaless(
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 596, in _decodeComponentsSchemaless
    for component in decodeFun(substrate, **options):
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 1778, in __call__
    for value in concreteDecoder.valueDecoder(
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 99, in valueDecoder
    for value in decodeFun(substrate, asn1Spec, tagSet, length, **options):
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 1778, in __call__
    for value in concreteDecoder.valueDecoder(
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 660, in valueDecoder
    for asn1Object in self._decodeComponentsSchemaless(
  File "/home/tux/pyasn1/pyasn1/codec/ber/decoder.py", line 604, in _decodeComponentsSchemaless
    componentTypes.add(component.tagSet)
AttributeError: 'NoneType' object has no attribute 'tagSet'

This change restores the previous code that will avoid this error.

Signed-off-by: Noel Power <noel.power@suse.com>